# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

# Cask bundles (brew install --cask)
cask 'visual-studio-code'

# Packages (brew install)
brew 'mas'
brew 'stow'
brew 'tree'

# Mac App Store (mas)
#mas 'Xcode', id: 497799835 // weird errors with xcode, try it just manually for now.

# Whalebrew packages (whalebrew install)
# whalebrew "whalebrew/wget"